name: novel_v3
description: "WebNovel App"
repository: https://github.com/ThanCoder/novelv3
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 3.6.0

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  pdfrx: ^2.2.8
  than_pkg: ^5.0.0
  t_widgets: ^1.7.4
  desktop_drop: ^0.6.1
  uuid: ^4.5.1
  provider: ^6.1.5+1
  archive: ^4.0.7
  t_html_parser: ^1.1.1
  t_server: ^2.2.0
  flutter_animate: ^4.5.2
  t_client: ^0.1.6
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.5.0
  # dart run change_app_package_name:main [com.new.package.name]
  flutter_launcher_icons: ^0.14.4
  # dart run flutter_launcher_icons
  flutter_lints: ^5.0.0

# dev lib
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo_3.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
    - CHANGELOG.md
    - README.md
    - pubspec.yaml
